### ISSUE TITLE
options.map

### ISSUE THREAD

**Issue by TheKnarf** [digitalie/one-loader#46] opened 2020-08-07 06:11 UTC
In the example you set `options.map` to the following:

```
options: {
   map: {
      'text/css': ['style-loader', 'css-loader'],
      'javascript': 'babel-loader'
   }
}
```

But this seem a bit odd to me, given that the sections are called `style` and `script, wouldn't this make more sense:

```
options: {
   map: {
      'style': ['style-loader', 'css-loader'],
      'script': 'babel-loader'
   }
}
```

Especially in regards to #44 if we want to add more types of sections. It seems that the map-option should be named the same as sections.

**Comment by Zauberfisch** [comment] 2020-08-08 08:43
I disagree. I think using the type is much better.

**Comment by MunGell** [comment] 2020-08-20 21:01
Hi @TheKnarf 

Thanks for the suggestion, the map was created that way, so it can allow in future to have different flavours of `style` and `script` tags.

For example, <script type="typescript"> can have loaders for typescript compilation, while `<style type="text/less">` can have code in LESS in it.

Please let me know if it makes sense!

**Comment by TheKnarf** [comment] 2020-08-21 06:26
Sure, but why would I limit myself to have `<script>`- and `<style>`-tags? Couldn't I have some kind of `<test>`-tag for unit tests, etc.

**Comment by MunGell** [comment] 2020-08-21 06:40
Looks like this issue is duplicate of #44 at this stage, closing it now.

**Closed by MunGell** 2020-08-21 06:40 UTC
